server:
  port: 9001
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dummy_db
    username: root
    password: system0705@!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
